openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /classifica:
    get:
      summary: restituisce la classifica generale
      operationId: getClassifica
      tags:
        - ClassificaGenerale
      responses:
        '200':
          description: l'oggetto classifica
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Classifica"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pronostici:
    get:
      summary: restituisce la lista dei pronostici
      operationId: getPronostici
      tags:
        - ClassificaGenerale
      responses:
        '200':
          description: la lista dei pronostici
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListaPronostici"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /partite:
    get:
      parameters:
        - name: limit
          in: query
          description: limit
          required: false
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          description: offset
          required: false
          schema:
            type: integer
            format: int64
        - name: data_da
          in: query
          description: data iniziale
          required: false
          schema:
            type: string
            format: date-time
        - name: data_a
          in: query
          description: data finale
          required: false
          schema:
            type: string
            format: date-time
      summary: restituisce la lista delle partite filtrate
      operationId: listPartite
      tags:
        - ProssimiIncontri
      responses:
        '200':
          description: la lista delle partite
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListaPartite"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /partite/{id_partita}:
    get:
      parameters:
        - name: id_partita
          in: path
          description: identificativo della partita
          required: true
          schema:
            type: string
      summary: restituisce la partita
      operationId: getPartita
      tags:
        - ProssimiIncontri
      responses:
        '200':
          description: la partita
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Partita"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /partite/{id_partita}/pronostici:
    get:
      parameters:
        - name: id_partita
          in: path
          description: identificativo della partita
          required: true
          schema:
            type: string
      summary: restituisce i pronostici relativi alla partita
      operationId: getPronosticiPartita
      tags:
        - ProssimiIncontri
      responses:
        '200':
          description: pronostici per partita
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListaPronosticiPartita"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /partite/{id_partita}/distribuzione/{tipo}:
    get:
      parameters:
        - name: id_partita
          in: path
          description: identificativo della partita
          required: true
          schema:
            type: string
        - name: tipo
          in: path
          description: tipo distribuzione
          required: true
          schema:
            $ref: "#/components/schemas/TipoDistribuzione"
      summary: restituisce la distribuzione per risultato o risultato esatto su una partita
      operationId: getDistribuzionePartita
      tags:
        - ProssimiIncontri
      responses:
        '200':
          description: distribuzione per partita
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Grafico"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Classifica:
      type: array
      items:
        $ref: "#/components/schemas/Pronostico"
    Pronostico:
      type: object
      properties:
        Giocatore:
          $ref: "#/components/schemas/Giocatore"
        punti:
          type: integer
          format: int32
        squadra_vincente:
          $ref: "#/components/schemas/Squadra"
    ListaPartite:
      type: array
      items:
        $ref: "#/components/schemas/Partita"
    ListaPronosticiPartita:
      type: array
      items:
        $ref: "#/components/schemas/PronosticoPartita"
    ListaPronostici:
      type: array
      items:
        $ref: "#/components/schemas/Pronostico"
    PronosticoPartita:
      type: object
      properties:
        partita:
          $ref: "#/components/schemas/Partita"
        pronostico:
          $ref: "#/components/schemas/PronosticoRisultato"
        giocatore:
          $ref: "#/components/schemas/Giocatore"
    Giocatore:
      type: object
      properties:
        id_giocatore:
          type: string
        nome:
          type: string
        link:
          type: string
        categoria:
          type: string
    PronosticoRisultato:
      type: object
      properties:
        goal_home:
          type: integer
          format: int32
        goal_away:
          type: integer
          format: int32
    Partita:
      type: object
      properties:
        id_partita:
          type: string
        descrizione:
          type: string
        stadio:
          $ref: "#/components/schemas/Stadio"
        casa:
          $ref: "#/components/schemas/Squadra"
        trasferta:
          $ref: "#/components/schemas/Squadra"
        data:
          type: string
          format: date-time
    Stadio:
      type: object
      properties:
        nome:
          type: string
        link:
          type: string
    Squadra:
      type: object
      properties:
        nome:
          type: string
        bandiera:
          type: string
    TipoDistribuzione:
      type: string
      enum:
        - 1X2
        - RISULTATO
    Grafico:
      type: object
      properties:
        distribuzioni:
          type: array
          items:
            $ref: "#/components/schemas/Distribuzione"
    Distribuzione:
      type: object
      properties:
        nome:
          type: string
        valore:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
